site_name: Meine VBA-Funktionen
site_url: https://marino222.github.io/VBA-Library/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.instant
    - toc.integrate

nav:
  - Dateipfad Funktionen:
    - ExtractFileNameFromPath: #extractfilenamefrompath
    - ChangeFileExtension: #changefileextension
  - PDM Funktionen:
    - FileExistsInPDM: #fileexistsinpdm
    - GetFilePathFromIEdmFile: #getfilepathfromiedmfile
