site_name: VBA-Funktionen
site_url: https://marino222.github.io/VBA-Library/
use_directory_urls: false

theme:
  name: material
  highlightjs: false
  features:
    - navigation.instant
    - toc.integrate
    - content.code.copy
    

nav:
  - Funktionen: index.md

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true    # Build-Zeit Highlighting mit Pygments aktivieren
      pygments_lang_class: true  # Sprach-Klasse ans <code> hängen
      line_spans: "__span"       # notwendig, damit jede Zeile in <span> kommt
      anchor_linenums: true      # falls du Zeilennummern nutzt
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
