site_name: Meine VBA-Funktionen
site_url: https://marino222.github.io/VBA-Library/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.instant
    - toc.integrate

nav:
  - Array-Funktionen:
    - IsInArray: VBA_Functions.md#isinarray
    - IsElementUnique: VBA_Functions.md#iselementunique
  - Datei-/Pfad-Funktionen:
    - ExtractFileNameFromPath: VBA_Functions.md#extractfilenamefrompath
    - ChangeFileExtension: VBA_Functions.md#changefileextension
  - PDM-/IEdm-Funktionen:
    - FileExistsInPDM: VBA_Functions.md#fileexistsinpdm
    - GetFilePathFromIEdmFile: VBA_Functions.md#getfilepathfromiedmfile
