site_name: VBA-Funktionen
site_url: https://marino222.github.io/VBA-Library/
use_directory_urls: false

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - toc.integrate
    - content.code.copy

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: false
      pygments_style: monokai
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: false
    

nav:
  - Code: index.md
  - Info: info.md

extra_css:
  - css/extra.css

