site_name: VBA-Funktionen
site_url: https://marino222.github.io/VBA-Library/
use_directory_urls: false

theme:
  name: material
  highlightjs: true
  highlightjs_languages:
    - vbnet
  features:
    - navigation.instant
    - toc.integrate
    - content.code.copy
    

nav:
  - Funktionen: index.md

markdown_extensions:
  - codehilite:
      guess_lang: false    
  - pymdownx.highlight: 
      anchor_linenums: true
