site_name: Meine VBA-Funktionen
site_url: https://marino222.github.io/VBA-Library/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.instant
    - toc.integrate

nav:
  - Array-Funktionen:
    - IsInArray: index.md#isinarray
    - IsElementUnique: index.md#iselementunique
  - Datei-/Pfad-Funktionen:
    - ExtractFileNameFromPath: index.md#extractfilenamefrompath
    - ChangeFileExtension: index.md#changefileextension
  - PDM-/IEdm-Funktionen:
    - FileExistsInPDM: index.md#fileexistsinpdm
    - GetFilePathFromIEdmFile: index.md#getfilepathfromiedmfile
