site_name: VBA-Funktionen
site_url: https://marino222.github.io/VBA-Library/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.instant
    - toc.integrate

nav:
  - Funktionen: index.md

markdown_extensions:
  - codehilite:
      guess_lang: false
      pygments_style: monokai
